### ISSUE TITLE
True Proof logic

### ISSUE THREAD

**Issue by shaybrow** [401Triceratops/true-proof#11]

**Comment by baxance** [comment]
- [x] Simple proofing with Temp/Hydrometer reading 5/24
- [x] Interpolated proofing with above + instrument correction factors 5/24
- [x] Proof calculated dynamically as input fields change 5/25
- [x] User input handled, limited input fields to temp/proof limits (1°-100°F, 1°-206° Proof) 5/25
- [x] Null proof values from accepted input limits handled, user requested to try again 5/25

**Comment by baxance** [comment]
- [ ] Add `save` button to calculator, save calculated proof + input values to DB 5/26
- [ ] Build `MeasurementDetailActivity` that shows interpolation of proof and "notes" input field 5/26
- [ ] Add HH:MM:SS clock to `TakeMeasurementActivity`, specific time is saved with saved measurements 5/26
- [ ] Resource links to TTB regulations, gauging manual and interpolation tables. Open in browse 5/26
